### ISSUE TITLE
GUI doesn't show up normally on Debian bookworm

### ISSUE THREAD

**Issue by jkroll20** [FrodeSolheim/fs-uae-launcher#149]
The GUI looks all messed up :/
![image](https://user-images.githubusercontent.com/244574/197359098-b039a4a7-fe6b-40b8-9c2b-e742f4d61ef1.png)

Lots of stacktraces in the terminal like the following:
<pre>
...
Unhandled exception detected in thread MainThread:
  TypeError:widget.py:set_position_and_size:160

Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsui/qt/Panel.py", line 117, in showEvent
    self.owner().on_resize()
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 203, in on_resize
    self.layout.set_size(self.get_size())
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 181, in set_size
    self.update()
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 310, in update
    child.element.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 160, in set_position_and_size
    self.widget().setGeometry(position[0], position[1], size[0], size[1])
TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 2 has unexpected type 'float'

Unhandled exception detected in thread MainThread:
  TypeError:widget.py:set_position_and_size:160

Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsui/qt/Panel.py", line 117, in showEvent
    self.owner().on_resize()
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 203, in on_resize
    self.layout.set_size(self.get_size())
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 181, in set_size
    self.update()
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 310, in update
    child.element.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 160, in set_position_and_size
    self.widget().setGeometry(position[0], position[1], size[0], size[1])
TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 2 has unexpected type 'float'

[IMAGES] ImageLoader.on_quit_signal
[IMAGES] ImageLoader.on_quit_signal

Unhandled exception detected in thread MainThread:
  TypeError:widget.py:set_position_and_size:160

Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsui/qt/Panel.py", line 117, in showEvent
    self.owner().on_resize()
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 203, in on_resize
    self.layout.set_size(self.get_size())
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 181, in set_size
    self.update()
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 310, in update
    child.element.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/common/group.py", line 52, in set_position_and_size
    self.layout.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 186, in set_position_and_size
    self.update()
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 310, in update
    child.element.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 186, in set_position_and_size
    self.update()
  File "/usr/share/fs-uae-launcher/fsui/common/layout.py", line 310, in update
    child.element.set_position_and_size(position, size)
  File "/usr/share/fs-uae-launcher/fsui/qt/widget.py", line 160, in set_position_and_size
    self.widget().setGeometry(position[0], position[1], size[0], size[1])
TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 2 has unexpected type 'float'
...
</pre>

I thought it could be some incompatibility with an external module, possibly pyqt5. I have 5.15.7+dfsg-1 installed with apt. I tried making a venv and installing earlier versions down to 5.10 or so. No success.

**Comment by FrodeSolheim** [comment]
Yes, there is an int/float-conversion bug in the Launcher that makes it incompatible with newer versions of PyQt. This is fixed in the latest FS-UAE Launcher versions (3.1.x).

https://fs-uae.net/download#linux

**Comment by jkroll20** [comment]
good to know. thanks!
