### ISSUE TITLE
OAGD DatabaseRefreshTask fails

### ISSUE THREAD

**Issue by norganna** [FrodeSolheim/fs-uae-launcher#15]
When initially logging into my OAGD account, the login succeeds and begins downloading the database, however after a while it fails with the message:

    DatabaseRefreshTask failed with exception
    'could not find parent a02169f6038d5-55e4-90a8-ba2608229693'.
    See log file for details

I have taken a look in the log file for launcher but cannot see anything related. An excerpt:

    <Task "DatabaseRefreshTask"> starting
    http://oagd.net/api/sync/1
    opening database /Volumes/Store/Games/FS-UAE/Data/Database.sqlite
    http://oagd.net/games/api/1/user_ratings?from=2012-01-01+00%3A00%3A00
      processing 0 entries
      0.00 seconds
    http://oagd.net/games/api/1/user_ratings?from=2012-01-01+00%3A00%3A00
    no more changes
    BaseDatabase.commit
    opening database /Volumes/Store/Games/FS-UAE/Cache/oagd.net.sqlite
    http://oagd.net/api/game-sync/1?last=0
      0.02 seconds
    http://oagd.net/api/game-sync/1?last=58679
      0.02 seconds
    http://oagd.net/api/game-sync/1?last=59516
      0.02 seconds
    http://oagd.net/api/game-sync/1?last=60257
    IncompleteRead(1809 bytes read, 10566 more expected)
      0.00 seconds
    http://oagd.net/api/game-sync/1?last=2020990776
    no more changes
    http://oagd.net/api/1/ratings?from=2012-01-01+00%3A00%3A00
      processing 1000 entries
      0.03 seconds
    http://oagd.net/api/1/ratings?from=2014-04-24+10%3A55%3A07
      processing 1000 entries
      0.03 seconds
    -----8<----- SNIP 66 similar lines SNIP -----8<----- 
    http://oagd.net/api/1/ratings?from=2014-04-24+11%3A05%3A52
      processing 1000 entries
      0.04 seconds
    http://oagd.net/api/1/ratings?from=2014-04-24+11%3A06%3A18
      processing 1000 entries
      0.04 seconds

I am using the 2.5.23dev version.

**Comment by FrodeSolheim** [comment]
Hi, I think there is a bug somewhere which "allows" the database to get into an invalid state. As you discovered, starting from scratch (but it would also suffice to just delete the file oagd.net.sqlite) "fixes" it. I'll reopen the bug report so other people can find it (until the issue is resolved).

**Comment by RichAyotte** [comment]
On a fresh install, I'm seeing this possibly related error.
```
extract search terms for: Alien Strike
word: alien
- new_word: alien
- sub_words: ['alien']
- combinations:
  ['alien']
word: strike
- new_word: strike
- sub_words: ['strike']
- combinations:
  ['strike']
new words: ['alien', 'strike']
terms {'strike', 'alieng'}
BaseDatabase.commit
Database.rollback
Database.rollback
<Task "DatabaseRefreshTask"> failed 'could not find parent 21989f4d-a2ee-542d-8604-67fd924b97be of game 5989c38f-e5e5-5a70-af11-5ea96b75e006'
Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsbc/task.py", line 59, in __run
    self.run()
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 24, in run
    self._run(database)
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 55, in _run
    scanner.scan(database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 115, in scan
    self.scan_game_database(helper, database_name, game_database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 188, in scan_game_database
    doc = game_database.get_game_values(variant_id)
  File "/usr/share/fs-uae-launcher/fsgs/GameDatabase.py", line 149, in get_game_values
    next_parent_uuid, game_uuid))
Exception: could not find parent 21989f4d-a2ee-542d-8604-67fd924b97be of game 5989c38f-e5e5-5a70-af11-5ea96b75e006
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
Database.__del__
```
OS: Debian Sid
FS-UAE: 2.8.0
Python: 2.7.13
sqlite3: 3.16.2

**Comment by bettachini** [comment]
Tried to delete all .sqlite files in the FS-UAE directory but the database fails to update.

`word: nation
- new_word: nation
- sub_words: ['nation']
- combinations:
  ['nation']
new words: ['utopia', 'the', 'creation', 'of', 'a', 'nation']
terms {'creationg', 'nationg', 'utopia'}
BaseDatabase.commit
Database.rollback
Database.rollback
<Task "DatabaseRefreshTask"> failed 'could not find parent 21989f4d-a2ee-542d-8604-67fd924b97be of game 5989c38f-e5e5-5a70-af11-5ea96b75e006'
Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsbc/task.py", line 59, in __run
    self.run()
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 24, in run
    self._run(database)
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 55, in _run
    scanner.scan(database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 115, in scan
    self.scan_game_database(helper, database_name, game_database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 188, in scan_game_database
    doc = game_database.get_game_values(variant_id)
  File "/usr/share/fs-uae-launcher/fsgs/GameDatabase.py", line 149, in get_game_values
    next_parent_uuid, game_uuid))
Exception: could not find parent 21989f4d-a2ee-542d-8604-67fd924b97be of game 5989c38f-e5e5-5a70-af11-5ea96b75e006
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
Database.__del__
BaseDatabase.__del__
`

OS: Debian Stretch
FS-UAE: 2.8.0
Python: 2.7.13

**Comment by ftoledo** [comment]
Same here on stretch

 ``` 
opening database /home/ragnarok/Documentos/FS-UAE/Data/Databases/Locker.sqlite
locker already up to date
opening database /home/ragnarok/Documentos/FS-UAE/Data/Databases/Files.sqlite
Database.rollback
Database.rollback
<Task "DatabaseRefreshTask"> failed 'could not find parent b9ec092c-f912-528e-97a3-ad822deb40c5 of game 58869de9-955a-55c3-8b15-fbdf15c3d128'
Traceback (most recent call last):
  File "/usr/share/fs-uae-launcher/fsbc/task.py", line 59, in __run
    self.run()
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 24, in run
    self._run(database)
  File "/usr/share/fs-uae-launcher/fsgs/ogd/refresh.py", line 55, in _run
    scanner.scan(database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 115, in scan
    self.scan_game_database(helper, database_name, game_database)
  File "/usr/share/fs-uae-launcher/launcher/game_scanner.py", line 188, in scan_game_database
    doc = game_database.get_game_values(variant_id)
  File "/usr/share/fs-uae-launcher/fsgs/GameDatabase.py", line 149, in get_game_values
    next_parent_uuid, game_uuid))
Exception: could not find parent b9ec092c-f912-528e-97a3-ad822deb40c5 of game 58869de9-955a-55c3-8b15-fbdf15c3d128
BaseDatabase.__del__
Database.__del__
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
BaseDatabase.__del__
```

**Comment by ftoledo** [comment]
any workaround?
