### ISSUE TITLE
TypeError on Linux Mint built from source.

### ISSUE THREAD

**Issue by sf97ahgf** [FrodeSolheim/fs-uae-launcher#162]
Python version is 3.10.12
Linux Mint version: Linux Mint virginia 21.3 x86_64
```
arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 2 has unexpected type 'float'

Traceback (most recent call last):
  File "/home/user/fs-uae-launcher/fswidgets/widget.py", line 133, in eventFilter
    self.on_show()
  File "/home/user/fs-uae-launcher/fswidgets/widget.py", line 647, in on_show
    self.on_resize()
  File "/home/user/fs-uae-launcher/fswidgets/widget.py", line 641, in on_resize
    self.layout.set_position((x, y))
  File "/home/user/fs-uae-launcher/fsui/common/layout.py", line 211, in set_position
    self.update()
  File "/home/user/fs-uae-launcher/fsui/common/layout.py", line 348, in update
    child.element.set_position_and_size(position, size)
  File "/home/user/fs-uae-launcher/fswidgets/widget.py", line 760, in set_position_and_size
    self.setPositionAndSize(position, size)
  File "/home/user/fs-uae-launcher/fswidgets/widget.py", line 355, in setPositionAndSize
    self.qwidget.setGeometry(position[0], position[1], size[0]), size[1])
TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'int'
  setGeometry(self, int, int, int, int): argument 2 has unexpected type 'float'
```
I think it stems from the fact that 3.10 is a bit old.
![image](https://github.com/user-attachments/assets/e9e2e76c-9c5f-4304-8d4c-5da0c791e0db)

**Comment by FrodeSolheim** [comment]
Do you still experience the issue with the latest source release? FS-UAE Launcher 3.2.20?
