### ISSUE TITLE
Launcher failing to start (missing GUID in joystick description)

### ISSUE THREAD

**Issue by dnlopez** [FrodeSolheim/fs-uae-launcher#29]
Just upgraded fs-uae-launcher from 2.5.30dev to 2.7.1dev, and it now fails to start. I'm using Arch Linux 64-bit. I've included the full output from the program below, but the problem seems to be that fs-uae-device-helper on my system returns this:
```
# listing keyboards
K: Keyboard
# listing mice
M: Mouse
# listing joysticks
# SDL_NumJoysticks(): 1
J: HID 6666:0667
   Buttons: 16 Hats: 0 Axes: 4 Balls: 0
# listing joysticks done
```
and then the launcher in DeviceManager.py has this code:
```
            if line.startswith("Buttons:"):
                parts = line.split(" ")
                buttons = int(parts[1])
                hats = int(parts[3])
                axes = int(parts[5])
                balls = int(parts[7])
                guid = parts[9]
                cls.joystick_data[last_joystick] = \
                    buttons, hats, axes, balls, guid
```
that is parsing the "Buttons:"... line but the list index is out of range when it comes to the GUID because there isn't one there.

I also got Arch to do a system-wide upgrade of all packages today so it could be that something changed in SDL or similar.

To get it working for myself I changed the guid line to "guid = None" and it seems to run OK though I realise it might not be ideal.

---------
Full startup log:
```
daniel [ ~/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher ]$ ./fs-uae-launcher 
executable_dir
sys.executable = /usr/bin/python3
using sys.argv[0] instead of python interpreter path
.
/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/.
executable_dir = /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/Portable.ini
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/Portable.ini
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/Portable.ini
checking /mnt/gear/download/archbuilds/emulator/Portable.ini
checking /mnt/gear/download/archbuilds/Portable.ini
checking /mnt/gear/download/Portable.ini
checking /mnt/gear/Portable.ini
checking /mnt/Portable.ini
checking /Portable.ini
no Portable.ini found in search path
base_dir not decided yet, checking FS_UAE_BASE_DIR
using default base_dir
- checking /home/daniel/.config/fs-uae-launcher/base-dir
- checking /home/daniel/.config/fs-uae/base-dir
base dir is /home/daniel/FS-UAE
fs-uae-launcher
2.7.1dev
enabling except hook
enable tread exception handler
uname_result(system='Linux', node='ENO', release='4.1.6-1-ARCH', version='#1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015', machine='x86_64', processor='')
['./fs-uae-launcher']
FS-UAE Launcher 2.7.1dev
looking up resource res/16/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/16/fs-uae-launcher.png
* checking for data dir ./share/fs-uae-launcher
* checking for data dir /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/share/fs-uae-launcher
data dirs: ['/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher', './share/fs-uae-launcher']
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/fs-uae-launcher.png
looking up resource res/22/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/22/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/22/fs-uae-launcher.png
- checking ./share/fs-uae-launcher/fs_uae_launcher/res/22/fs-uae-launcher.png
resource_filename("fs_uae_launcher", "res/22/fs-uae-launcher.png")
looking up resource res/24/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/24/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/24/fs-uae-launcher.png
- checking ./share/fs-uae-launcher/fs_uae_launcher/res/24/fs-uae-launcher.png
resource_filename("fs_uae_launcher", "res/24/fs-uae-launcher.png")
looking up resource res/32/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/32/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/32/fs-uae-launcher.png
looking up resource res/64/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/64/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/64/fs-uae-launcher.png
looking up resource res/128/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/128/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/128/fs-uae-launcher.png
looking up resource res/256/fs-uae-launcher.png
- package: fs_uae_launcher
resource_name res/256/fs-uae-launcher.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/256/fs-uae-launcher.png
settings file /home/daniel/FS-UAE/Data/Settings.ini does not exist
FONT: Default is Sans 10
FSUAELauncherApplication.start
loading last config from '/home/daniel/FS-UAE/Data/Settings.ini'
settings file does not exist
initialize_locale language = 
locale is en_GB
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/share/fs-uae-launcher/share-dir
bindtextdomain fs-uae-launcher: /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/share/locale
find translations for en_GB in local directory /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/share/locale
path to mo file: None
translations object: <gettext.NullTranslations object at 0x7f738341cf98>
config_startup_scan /home/daniel/FS-UAE/Configurations
{'swap_ctrl_keys': '', 'floppy_drive_volume': '', 'config_search': '', 'config_xml_path': '', 'database_show_adult': '', 'irc_server': '', 'config_name': 'Unnamed Configuration', 'last_hd_dir': '', 'database_feature': '', 'zoom': '', 'audio_buffer_target_size': '', 'texture_filter': '', 'monitor': '', 'fullscreen': '', 'database_show_games': '', 'database_email': '', 'last_scan': '', 'irc_nick': '', 'last_settings_page': '', 'config_refresh': '', 'texture_format': '', 'builtin_configs': '', 'last_cd_dir': '', 'language': '', 'game_uuid': '', 'game_list_uuid': '', '__netplay_ready': '', 'config_changed': '0', 'initial_input_grab': '', 'video_sync': '', 'floppy_drive_volume_empty': '', 'primary_joystick': '', 'scan_configs': '1', 'database_password': '', 'secondary_joystick': '', 'configurations_dir_mtime': '', 'keep_aspect': '', 'maximized': '0', 'stereo_separation': '', 'scan_files': '1', 'launcher_theme': '', 'fsaa': '', 'config_feature': '', 'audio_frequency': '', 'device_id': '', 'config_base': '', 'last_rom_dir': '', 'netplay_feature': '', 'kickstart_setup': '', 'video_sync_method': '', 'database_server': '', 'netplay_tag': '', 'database_username': '', 'middle_click_ungrab': '', 'config_path': '', 'mouse_speed': '', 'database_auth': '', 'scan_roms': '1', 'last_floppy_dir': '', 'parent_uuid': '', 'search_path': '', 'low_latency_vsync': '', 'video_format': '', 'kickstarts_dir_mtime': '', 'automatic_input_grab': ''}
... database.find_local_configurations
opening database /home/daniel/FS-UAE/Data/Database.sqlite
... walk configs_dir
... commit
BaseDatabase.commit
settings set configurations_dir_mtime to 1443298237+30
kickstart_startup_scan
... database.find_local_roms
opening database /home/daniel/FS-UAE/Cache/Files.sqlite
... walk kickstarts_dir
{}
... commit
BaseDatabase.commit
settings set kickstarts_dir_mtime to 1443298237
opening database /home/daniel/FS-UAE/Cache/Locker.sqlite
BaseDatabase.commit
using screen size (1024, 768)
looking up resource res/main_menu.png
- package: fs_uae_launcher
resource_name res/main_menu.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/main_menu.png
looking up resource res/new_button.png
- package: fs_uae_launcher
resource_name res/new_button.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/new_button.png
VerticalItemView selectionModel =  <PyQt5.QtCore.QItemSelectionModel object at 0x7f7383406ca8>
looking up resource res/16/controller.png
- package: fs_uae_launcher
resource_name res/16/controller.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/controller.png
looking up resource res/fsuae_config_16.png
- package: fs_uae_launcher
resource_name res/fsuae_config_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/fsuae_config_16.png
search for 
extract search terms for: 
word: 
- new_word: 
- sub_words: ['']
new words: ['']
terms {''}
Database.find_games_new search = ''
SELECT DISTINCT uuid, name, platform, year, publisher, front_image, title_image, screen1_image, screen2_image, screen3_image, screen4_image, screen5_image, have, path, sort_key, subtitle, thumb_image, backdrop_image FROM game WHERE have >= 1 AND adult IS NULL ORDER BY sort_key, platform
looking up resource res/16/arrow_down_yellow.png
- package: fs_uae_launcher
resource_name res/16/arrow_down_yellow.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/arrow_down_yellow.png
looking up resource res/16/arrow_down_green.png
- package: fs_uae_launcher
resource_name res/16/arrow_down_green.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/arrow_down_green.png
looking up resource res/16/blank.png
- package: fs_uae_launcher
resource_name res/16/blank.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/blank.png
looking up resource res/fsuae_config_16.png
- package: fs_uae_launcher
resource_name res/fsuae_config_16.png
looking up resource res/adf_game_16.png
- package: fs_uae_launcher
resource_name res/adf_game_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/adf_game_16.png
looking up resource res/ipf_game_16.png
- package: fs_uae_launcher
resource_name res/ipf_game_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/ipf_game_16.png
looking up resource res/cd_game_16.png
- package: fs_uae_launcher
resource_name res/cd_game_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/cd_game_16.png
looking up resource res/hd_game_16.png
- package: fs_uae_launcher
resource_name res/hd_game_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/hd_game_16.png
looking up resource res/16/delete_grey.png
- package: fs_uae_launcher
resource_name res/16/delete_grey.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/delete_grey.png
looking up resource res/16/blank.png
- package: fs_uae_launcher
resource_name res/16/blank.png
looking up resource res/16/bullet.png
- package: fs_uae_launcher
resource_name res/16/bullet.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/bullet.png
looking up resource res/16/arrow_down_yellow.png
- package: fs_uae_launcher
resource_name res/16/arrow_down_yellow.png
looking up resource res/16/arrow_down_green.png
- package: fs_uae_launcher
resource_name res/16/arrow_down_green.png
looking up resource res/16/thumb_up_mod.png
- package: fs_uae_launcher
resource_name res/16/thumb_up_mod.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/thumb_up_mod.png
looking up resource res/16/thumb_down_mod.png
- package: fs_uae_launcher
resource_name res/16/thumb_down_mod.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/thumb_down_mod.png
looking up resource res/rating_fav_16.png
- package: fs_uae_launcher
resource_name res/rating_fav_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/rating_fav_16.png
settings set game_uuid to  (no change)
looking up resource res/16/thumb_down_2.png
- package: fs_uae_launcher
resource_name res/16/thumb_down_2.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/thumb_down_2.png
looking up resource res/16/thumb_up_2.png
- package: fs_uae_launcher
resource_name res/16/thumb_up_2.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/thumb_up_2.png
looking up resource res/16/rating_fav_2.png
- package: fs_uae_launcher
resource_name res/16/rating_fav_2.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/rating_fav_2.png
looking up resource res/save_button.png
- package: fs_uae_launcher
resource_name res/save_button.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/save_button.png
using screen size (1024, 768)
looking up resource res/16/warning_2.png
- package: fs_uae_launcher
resource_name res/16/warning_2.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/16/warning_2.png
looking up resource res/windowed_16.png
- package: fs_uae_launcher
resource_name res/windowed_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/windowed_16.png
looking up resource res/fullscreen_16.png
- package: fs_uae_launcher
resource_name res/fullscreen_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/fullscreen_16.png
looking up resource res/eject_button.png
- package: fs_uae_launcher
resource_name res/eject_button.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/eject_button.png
looking up resource res/browse_file_16.png
- package: fs_uae_launcher
resource_name res/browse_file_16.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/browse_file_16.png
looking up resource res/eject_button.png
- package: fs_uae_launcher
resource_name res/eject_button.png
looking up resource res/browse_file_16.png
- package: fs_uae_launcher
resource_name res/browse_file_16.png
looking up resource res/refresh_button.png
- package: fs_uae_launcher
resource_name res/refresh_button.png
- checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/res/refresh_button.png
FIXME: ComboBox not respecting read_only(because of missing lineEdit then
finding connected joysticks
FSUAE.start_with_args: ['--list']
application executable dir /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs-uae-device-helper
checking /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/../bin/fs-uae-device-helper
current dir (cwd):  /mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher
using fs-uae executable: fs-uae-device-helper
['fs-uae-device-helper', '--list']
b'# listing keyboards\nK: Keyboard\n# listing mice\nM: Mouse\n# listing joysticks\n# SDL_NumJoysticks(): 1\nJ: HID 6666:0667\n   Buttons: 16 Hats: 0 Axes: 4 Balls: 0\n# listing joysticks done\n'

Unhandled exception detected in thread MainThread:
  IndexError:DeviceManager.py:init_fsuae:114

Traceback (most recent call last):
  File "./fs-uae-launcher", line 10, in <module>
    main()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/main.py", line 170, in main
    if application.start():
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/FSUAELauncher.py", line 184, in start
    window = MainWindow(fsgs, icon=icon)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 108, in __init__
    self.create_column(2, min_width=right_width, expand=True)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 290, in create_column
    self.add_column_content(column)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 381, in add_column_content
    gettext("Config"), gettext("Main Configuration Options"))
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 500, in add_page
    instance = content_class(book)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainPanel.py", line 20, in __init__
    self.input_group = InputGroup(self)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputGroup.py", line 53, in __init__
    selector = InputSelector(self, i)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputSelector.py", line 49, in __init__
    self.rebuild_device_list()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputSelector.py", line 75, in rebuild_device_list
    for i, name in enumerate(DeviceManager.get_joystick_names()):
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 150, in get_joystick_names
    cls.init()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 70, in init
    cls.init_fsuae()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 114, in init_fsuae
    guid = parts[9]
IndexError: list index out of range


Unhandled exception detected in thread MainThread:
  IndexError:DeviceManager.py:init_fsuae:114

Traceback (most recent call last):
  File "./fs-uae-launcher", line 10, in <module>
    main()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/main.py", line 170, in main
    if application.start():
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/FSUAELauncher.py", line 184, in start
    window = MainWindow(fsgs, icon=icon)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 108, in __init__
    self.create_column(2, min_width=right_width, expand=True)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 290, in create_column
    self.add_column_content(column)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 381, in add_column_content
    gettext("Config"), gettext("Main Configuration Options"))
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainWindow.py", line 500, in add_page
    instance = content_class(book)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/MainPanel.py", line 20, in __init__
    self.input_group = InputGroup(self)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputGroup.py", line 53, in __init__
    selector = InputSelector(self, i)
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputSelector.py", line 49, in __init__
    self.rebuild_device_list()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/ui/config/InputSelector.py", line 75, in rebuild_device_list
    for i, name in enumerate(DeviceManager.get_joystick_names()):
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 150, in get_joystick_names
    cls.init()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 70, in init
    cls.init_fsuae()
  File "/mnt/gear/download/archbuilds/emulator/Commodore_Amiga/fs-uae-launcher-devel/fs-uae-launcher/fs_uae_launcher/DeviceManager.py", line 114, in init_fsuae
    guid = parts[9]
IndexError: list index out of range
```

**Comment by FrodeSolheim** [comment]
fs-uae-device-helper should also output the GUID value, so the problem isn't the launcher. The problem is fs-uae-device-helper. Most likely reason, too old version. Please make sure the fs-uae package (or whatever Arch package contains fs-uae-device-helper) is also updated to version 2.7.1dev!

 Example for what you should get when running fs-uae-device-helper --list:

    $ fs-uae-device-helper --list
    # listing keyboards
    K: Keyboard
    # listing mice
    M: Mouse
    M: Logitech USB Laser Mouse
    # listing joysticks
    # SDL_NumJoysticks(): 1
    J: Microsoft X-Box One pad
       Buttons: 11 Hats: 1 Axes: 6 Balls: 0 GUID: 030000005e040000d102000001010000
    # listing joysticks done

**Comment by dnlopez** [comment]
Ah right, I upgraded my fs-uae to 2.7.1dev and the problem is solved as you described. Sorry, I should have realised. Thanks!
